services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 3000
        API_BASE_URL: https://api.timlukfab.com
        NEXT_PUBLIC_API_BASE_URL: https://api.timlukfab.com
        NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY: pk_test_49e59d694b9f640b9fd2d1c41875ea5cfba533e0
        NEXT_PUBLIC_PAYSTACK_SECRET_KEY: sk_test_5df67ce9e6964fd220eb85a2399473ebdb0f9fc4
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
