FROM node:20-alpine

WORKDIR /app

# Define build arguments for each environment variable
ARG NODE_ENV
ARG API_BASE_URL
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
ARG NEXT_PUBLIC_PAYSTACK_SECRET_KEY

# Set environment variables using the build arguments
ENV NODE_ENV=${NODE_ENV}
ENV API_BASE_URL=${API_BASE_URL}
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=${NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY}
ENV NEXT_PUBLIC_PAYSTACK_SECRET_KEY=${NEXT_PUBLIC_PAYSTACK_SECRET_KEY}

COPY package*.json .

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]