FROM node:20-alpine

WORKDIR /app

# Define build arguments for each environment variable

ARG API_BASE_URL=https://api.timlukfab.com
ARG NEXT_PUBLIC_API_BASE_URL=https://api.timlukfab.com
ARG NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=pk_test_49e59d694b9f640b9fd2d1c41875ea5cfba533e0
ARG NEXT_PUBLIC_PAYSTACK_SECRET_KEY=sk_test_5df67ce9e6964fd220eb85a2399473ebdb0f9fc4
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51Q9JVVH7x9DO8cdOdMomj35ByQc05UvRR4uEiE91o7WSAyqA4ry8J0wvImPI3FzDJ6oN2IKE0oCvgLrs4NDvb7pI00BWyrLQrJ
ARG NEXT_PUBLIC_STRIPE_SECRET_KEY=sk_test_51Q9JVVH7x9DO8cdOsjDDgf3Zr1w9JmrHewKDaUXWkN4bExJGklqd0iqwuBoWiZ3HvZGCBxpWtVzABEIOANVCb2dS00IzsB4fML
ARG NEXT_PUBLIC_BASE_URL=https://timlukfab.onrender.com

# Set environment variables using the build arguments
ENV API_BASE_URL=${API_BASE_URL}
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=${NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY}
ENV NEXT_PUBLIC_PAYSTACK_SECRET_KEY=${NEXT_PUBLIC_PAYSTACK_SECRET_KEY}
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
ENV NEXT_PUBLIC_STRIPE_SECRET_KEY=${NEXT_PUBLIC_STRIPE_SECRET_KEY}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}

COPY package*.json .

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start"]