export const countryList = [
  { name: "Albania", code: "AL", dialingCode: "+355" },
  { name: "Åland Islands", code: "AX", dialingCode: "+358" },
  { name: "Algeria", code: "DZ", dialingCode: "+213" },
  { name: "American Samoa", code: "AS", dialingCode: "+1-684" },
  { name: "Andorra", code: "AD", dialingCode: "+376" },
  { name: "Angola", code: "AO", dialingCode: "+244" },
  { name: "Anguilla", code: "AI", dialingCode: "+1-264" },
  { name: "Antarctica", code: "AQ", dialingCode: "+672" },
  { name: "Antigua and Barbuda", code: "AG", dialingCode: "+1-268" },
  { name: "Argentina", code: "AR", dialingCode: "+54" },
  { name: "Armenia", code: "AM", dialingCode: "+374" },
  { name: "Aruba", code: "AW", dialingCode: "+297" },
  { name: "Australia", code: "AU", dialingCode: "+61" },
  { name: "Austria", code: "AT", dialingCode: "+43" },
  { name: "Azerbaijan", code: "AZ", dialingCode: "+994" },
  { name: "Bahamas (the)", code: "BS", dialingCode: "+1-242" },
  { name: "Bahrain", code: "BH", dialingCode: "+973" },
  { name: "Bangladesh", code: "BD", dialingCode: "+880" },
  { name: "Barbados", code: "BB", dialingCode: "+1-246" },
  { name: "Belarus", code: "BY", dialingCode: "+375" },
  { name: "Belgium", code: "BE", dialingCode: "+32" },
  { name: "Belize", code: "BZ", dialingCode: "+501" },
  { name: "Benin", code: "BJ", dialingCode: "+229" },
  { name: "Bermuda", code: "BM", dialingCode: "+1-441" },
  { name: "Bhutan", code: "BT", dialingCode: "+975" },
  { name: "Bolivia (Plurinational State of)", code: "BO", dialingCode: "+591" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ", dialingCode: "+599" },
  { name: "Bosnia and Herzegovina", code: "BA", dialingCode: "+387" },
  { name: "Botswana", code: "BW", dialingCode: "+267" },
  { name: "Bouvet Island", code: "BV", dialingCode: "+47" },
  { name: "Brazil", code: "BR", dialingCode: "+55" },
  { name: "British Indian Ocean Territory (the)", code: "IO", dialingCode: "+246" },
  { name: "Brunei Darussalam", code: "BN", dialingCode: "+673" },
  { name: "Bulgaria", code: "BG", dialingCode: "+359" },
  { name: "Burkina Faso", code: "BF", dialingCode: "+226" },
  { name: "Burundi", code: "BI", dialingCode: "+257" },
  { name: "Cabo Verde", code: "CV", dialingCode: "+238" },
  { name: "Cambodia", code: "KH", dialingCode: "+855" },
  { name: "Cameroon", code: "CM", dialingCode: "+237" },
  { name: "Canada", code: "CA", dialingCode: "+1" },
  { name: "Cayman Islands (the)", code: "KY", dialingCode: "+1-345" },
  { name: "Central African Republic (the)", code: "CF", dialingCode: "+236" },
  { name: "Chad", code: "TD", dialingCode: "+235" },
  { name: "Chile", code: "CL", dialingCode: "+56" },
  { name: "China", code: "CN", dialingCode: "+86" },
  { name: "Christmas Island", code: "CX", dialingCode: "+61" },
  { name: "Cocos (Keeling) Islands (the)", code: "CC", dialingCode: "+61" },
  { name: "Colombia", code: "CO", dialingCode: "+57" },
  { name: "Comoros (the)", code: "KM", dialingCode: "+269" },
  { name: "Congo (the Democratic Republic of the)", code: "CD", dialingCode: "+243" },
  { name: "Congo (the)", code: "CG", dialingCode: "+242" },
  { name: "Cook Islands (the)", code: "CK", dialingCode: "+682" },
  { name: "Costa Rica", code: "CR", dialingCode: "+506" },
  { name: "Croatia", code: "HR", dialingCode: "+385" },
  { name: "Cuba", code: "CU", dialingCode: "+53" },
  { name: "Curaçao", code: "CW", dialingCode: "+599" },
  { name: "Cyprus", code: "CY", dialingCode: "+357" },
  { name: "Czechia", code: "CZ", dialingCode: "+420" },
  { name: "Côte d'Ivoire", code: "CI", dialingCode: "+225" },
  { name: "Denmark", code: "DK", dialingCode: "+45" },
  { name: "Djibouti", code: "DJ", dialingCode: "+253" },
  { name: "Dominica", code: "DM", dialingCode: "+1-767" },
  { name: "Dominican Republic (the)", code: "DO", dialingCode: "+1-809" },
  { name: "Ecuador", code: "EC", dialingCode: "+593" },
  { name: "Egypt", code: "EG", dialingCode: "+20" },
  { name: "El Salvador", code: "SV", dialingCode: "+503" },
  { name: "Equatorial Guinea", code: "GQ", dialingCode: "+240" },
  { name: "Eritrea", code: "ER", dialingCode: "+291" },
  { name: "Estonia", code: "EE", dialingCode: "+372" },
  { name: "Eswatini", code: "SZ", dialingCode: "+268" },
  { name: "Ethiopia", code: "ET", dialingCode: "+251" },
  { name: "Falkland Islands (the) [Malvinas]", code: "FK", dialingCode: "+500" },
  { name: "Faroe Islands (the)", code: "FO", dialingCode: "+298" },
  { name: "Fiji", code: "FJ", dialingCode: "+679" },
  { name: "Finland", code: "FI", dialingCode: "+358" },
  { name: "France", code: "FR", dialingCode: "+33" },
  { name: "French Guiana", code: "GF", dialingCode: "+594" },
  { name: "French Polynesia", code: "PF", dialingCode: "+689" },
  { name: "French Southern Territories (the)", code: "TF", dialingCode: "+262" },
  { name: "Gabon", code: "GA", dialingCode: "+241" },
  { name: "Gambia (the)", code: "GM", dialingCode: "+220" },
  { name: "Georgia", code: "GE", dialingCode: "+995" },
  { name: "Germany", code: "DE", dialingCode: "+49" },
  { name: "Ghana", code: "GH", dialingCode: "+233" },
  { name: "Gibraltar", code: "GI", dialingCode: "+350" },
  { name: "Greece", code: "GR", dialingCode: "+30" },
  { name: "Greenland", code: "GL", dialingCode: "+299" },
  { name: "Grenada", code: "GD", dialingCode: "+1-473" },
  { name: "Guadeloupe", code: "GP", dialingCode: "+590" },
  { name: "Guam", code: "GU", dialingCode: "+1-671" },
  { name: "Guatemala", code: "GT", dialingCode: "+502" },
  { name: "Guernsey", code: "GG", dialingCode: "+44-1481" },
  { name: "Guinea", code: "GN", dialingCode: "+224" },
  { name: "Guinea-Bissau", code: "GW", dialingCode: "+245" },
  { name: "Guyana", code: "GY", dialingCode: "+592" },
  { name: "Haiti", code: "HT", dialingCode: "+509" },
  { name: "Heard Island and McDonald Islands", code: "HM", dialingCode: "+672" },
  { name: "Holy See (the)", code: "VA", dialingCode: "+39" },
  { name: "Honduras", code: "HN", dialingCode: "+504" },
  { name: "Hong Kong", code: "HK", dialingCode: "+852" },
  { name: "Hungary", code: "HU", dialingCode: "+36" },
  { name: "Iceland", code: "IS", dialingCode: "+354" },
  { name: "India", code: "IN", dialingCode: "+91" },
  { name: "Indonesia", code: "ID", dialingCode: "+62" },
  { name: "Iran (Islamic Republic of)", code: "IR", dialingCode: "+98" },
  { name: "Iraq", code: "IQ", dialingCode: "+964" },
  { name: "Ireland", code: "IE", dialingCode: "+353" },
  { name: "Isle of Man", code: "IM", dialingCode: "+44" },
  { name: "Israel", code: "IL", dialingCode: "+972" },
  { name: "Italy", code: "IT", dialingCode: "+39" },
  { name: "Jamaica", code: "JM", dialingCode: "+1-876" },
  { name: "Japan", code: "JP", dialingCode: "+81" },
  { name: "Jersey", code: "JE", dialingCode: "+44" },
  { name: "Jordan", code: "JO", dialingCode: "+962" },
  { name: "Kazakhstan", code: "KZ", dialingCode: "+7" },
  { name: "Kenya", code: "KE", dialingCode: "+254" },
  { name: "Kiribati", code: "KI", dialingCode: "+686" },
  { name: "Korea (the Democratic People's Republic of)", code: "KP", dialingCode: "+850" },
  { name: "Korea (the Republic of)", code: "KR", dialingCode: "+82" },
  { name: "Kuwait", code: "KW", dialingCode: "+965" },
  { name: "Kyrgyzstan", code: "KG", dialingCode: "+996" },
  { name: "Lao People's Democratic Republic (the)", code: "LA", dialingCode: "+856" },
  { name: "Latvia", code: "LV", dialingCode: "+371" },
  { name: "Lebanon", code: "LB", dialingCode: "+961" },
  { name: "Lesotho", code: "LS", dialingCode: "+266" },
  { name: "Liberia", code: "LR", dialingCode: "+231" },
  { name: "Libya", code: "LY", dialingCode: "+218" },
  { name: "Liechtenstein", code: "LI", dialingCode: "+423" },
  { name: "Lithuania", code: "LT", dialingCode: "+370" },
  { name: "Luxembourg", code: "LU", dialingCode: "+352" },
  { name: "Macao", code: "MO", dialingCode: "+853" },
  { name: "Madagascar", code: "MG", dialingCode: "+261" },
  { name: "Malawi", code: "MW", dialingCode: "+265" },
  { name: "Malaysia", code: "MY", dialingCode: "+60" },
  { name: "Maldives", code: "MV", dialingCode: "+960" },
  { name: "Mali", code: "ML", dialingCode: "+223" },
  { name: "Malta", code: "MT", dialingCode: "+356" },
  { name: "Marshall Islands (the)", code: "MH", dialingCode: "+692" },
  { name: "Martinique", code: "MQ", dialingCode: "+596" },
  { name: "Mauritania", code: "MR", dialingCode: "+222" },
  { name: "Mauritius", code: "MU", dialingCode: "+230" },
  { name: "Mayotte", code: "YT", dialingCode: "+262" },
  { name: "Mexico", code: "MX", dialingCode: "+52" },
  { name: "Micronesia (Federated States of)", code: "FM", dialingCode: "+691" },
  { name: "Moldova (the Republic of)", code: "MD", dialingCode: "+373" },
  { name: "Monaco", code: "MC", dialingCode: "+377" },
  { name: "Mongolia", code: "MN", dialingCode: "+976" },
  { name: "Montenegro", code: "ME", dialingCode: "+382" },
  { name: "Montserrat", code: "MS", dialingCode: "+1-664" },
  { name: "Morocco", code: "MA", dialingCode: "+212" },
  { name: "Mozambique", code: "MZ", dialingCode: "+258" },
  { name: "Myanmar", code: "MM", dialingCode: "+95" },
  { name: "Namibia", code: "NA", dialingCode: "+264" },
  { name: "Nauru", code: "NR", dialingCode: "+674" },
  { name: "Nepal", code: "NP", dialingCode: "+977" },
  { name: "Netherlands (the)", code: "NL", dialingCode: "+31" },
  { name: "New Caledonia", code: "NC", dialingCode: "+687" },
  { name: "New Zealand", code: "NZ", dialingCode: "+64" },
  { name: "Nicaragua", code: "NI", dialingCode: "+505" },
  { name: "Niger (the)", code: "NE", dialingCode: "+227" },
  { name: "Nigeria", code: "NG", dialingCode: "+234" },
  { name: "Niue", code: "NU", dialingCode: "+683" },
  { name: "Norfolk Island", code: "NF", dialingCode: "+672" },
  { name: "Northern Mariana Islands (the)", code: "MP", dialingCode: "+1-670" },
  { name: "Norway", code: "NO", dialingCode: "+47" },
  { name: "Oman", code: "OM", dialingCode: "+968" },
  { name: "Pakistan", code: "PK", dialingCode: "+92" },
  { name: "Palau", code: "PW", dialingCode: "+680" },
  { name: "Palestine, State of", code: "PS", dialingCode: "+970" },
  { name: "Panama", code: "PA", dialingCode: "+507" },
  { name: "Papua New Guinea", code: "PG", dialingCode: "+675" },
  { name: "Paraguay", code: "PY", dialingCode: "+595" },
  { name: "Peru", code: "PE", dialingCode: "+51" },
  { name: "Philippines (the)", code: "PH", dialingCode: "+63" },
  { name: "Pitcairn", code: "PN", dialingCode: "+64" },
  { name: "Poland", code: "PL", dialingCode: "+48" },
  { name: "Portugal", code: "PT", dialingCode: "+351" },
  { name: "Puerto Rico", code: "PR", dialingCode: "+1-787" },
  { name: "Qatar", code: "QA", dialingCode: "+974" },
  { name: "Republic of North Macedonia", code: "MK", dialingCode: "+389" },
  { name: "Romania", code: "RO", dialingCode: "+40" },
  { name: "Russian Federation (the)", code: "RU", dialingCode: "+7" },
  { name: "Rwanda", code: "RW", dialingCode: "+250" },
  { name: "Réunion", code: "RE", dialingCode: "+262" },
  { name: "Saint Barthélemy", code: "BL", dialingCode: "+590" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", code: "SH", dialingCode: "+290" },
  { name: "Saint Kitts and Nevis", code: "KN", dialingCode: "+1-869" },
  { name: "Saint Lucia", code: "LC", dialingCode: "+1-758" },
  { name: "Saint Martin (French part)", code: "MF", dialingCode: "+590" },
  { name: "Saint Pierre and Miquelon", code: "PM", dialingCode: "+508" },
  { name: "Saint Vincent and the Grenadines", code: "VC", dialingCode: "+1-784" },
  { name: "Samoa", code: "WS", dialingCode: "+685" },
  { name: "San Marino", code: "SM", dialingCode: "+378" },
  { name: "Sao Tome and Principe", code: "ST", dialingCode: "+239" },
  { name: "Saudi Arabia", code: "SA", dialingCode: "+966" },
  { name: "Senegal", code: "SN", dialingCode: "+221" },
  { name: "Serbia", code: "RS", dialingCode: "+381" },
  { name: "Seychelles", code: "SC", dialingCode: "+248" },
  { name: "Sierra Leone", code: "SL", dialingCode: "+232" },
  { name: "Singapore", code: "SG", dialingCode: "+65" },
  { name: "Sint Maarten (Dutch part)", code: "SX", dialingCode: "+1-721" },
  { name: "Slovakia", code: "SK", dialingCode: "+421" },
  { name: "Slovenia", code: "SI", dialingCode: "+386" },
  { name: "Solomon Islands", code: "SB", dialingCode: "+677" },
  { name: "Somalia", code: "SO", dialingCode: "+252" },
  { name: "South Africa", code: "ZA", dialingCode: "+27" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS", dialingCode: "+500" },
  { name: "South Sudan", code: "SS", dialingCode: "+211" },
  { name: "Spain", code: "ES", dialingCode: "+34" },
  { name: "Sri Lanka", code: "LK", dialingCode: "+94" },
  { name: "Sudan (the)", code: "SD", dialingCode: "+249" },
  { name: "Suriname", code: "SR", dialingCode: "+597" },
  { name: "Svalbard and Jan Mayen", code: "SJ", dialingCode: "+47" },
  { name: "Sweden", code: "SE", dialingCode: "+46" },
  { name: "Switzerland", code: "CH", dialingCode: "+41" },
  { name: "Syrian Arab Republic", code: "SY", dialingCode: "+963" },
  { name: "Taiwan (Province of China)", code: "TW", dialingCode: "+886" },
  { name: "Tajikistan", code: "TJ", dialingCode: "+992" },
  { name: "Tanzania, United Republic of", code: "TZ", dialingCode: "+255" },
  { name: "Thailand", code: "TH", dialingCode: "+66" },
  { name: "Timor-Leste", code: "TL", dialingCode: "+670" },
  { name: "Togo", code: "TG", dialingCode: "+228" },
  { name: "Tokelau", code: "TK", dialingCode: "+690" },
  { name: "Tonga", code: "TO", dialingCode: "+676" },
  { name: "Trinidad and Tobago", code: "TT", dialingCode: "+1-868" },
  { name: "Tunisia", code: "TN", dialingCode: "+216" },
  { name: "Turkey", code: "TR", dialingCode: "+90" },
  { name: "Turkmenistan", code: "TM", dialingCode: "+993" },
  { name: "Tuvalu", code: "TV", dialingCode: "+688" },
  { name: "Uganda", code: "UG", dialingCode: "+256" },
  { name: "Ukraine", code: "UA", dialingCode: "+380" },
  { name: "United Arab Emirates (the)", code: "AE", dialingCode: "+971" },
  { name: "United Kingdom of Great Britain and Northern Ireland (the)", code: "GB", dialingCode: "+44" },
  { name: "United States of America (the)", code: "US", dialingCode: "+1" },
  { name: "Uruguay", code: "UY", dialingCode: "+598" },
  { name: "Uzbekistan", code: "UZ", dialingCode: "+998" },
  { name: "Vanuatu", code: "VU", dialingCode: "+678" },
  { name: "Venezuela (Bolivarian Republic of)", code: "VE", dialingCode: "+58" },
  { name: "Viet Nam", code: "VN", dialingCode: "+84" },
  { name: "Western Sahara", code: "EH", dialingCode: "+212" },
  { name: "Yemen", code: "YE", dialingCode: "+967" },
  { name: "Zambia", code: "ZM", dialingCode: "+260" },
  { name: "Zimbabwe", code: "ZW", dialingCode: "+263" }
];



